# Pipeline Code gotten and modified from official Azure website with the links below
# https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive
# https://learn.microsoft.com/en-us/azure/app-service/deploy-azure-pipelines?tabs=yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Build the Azure web app
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
# Publish the web app package
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
# Deploy the web app automatically 
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azureconnectionforpipeline' #Created this azure connection service for my Azure subscription
    appType: 'webAppLinux'
    appName: 'geolocationwebapp' #My Web App Name
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'